"""Re-exports every view so callers can use ``from scoring import views``."""

from .api import api_attack_types, api_scores, api_team_detail
from .config import recalculate_scores, scoring_config, sync_metadata, sync_scores
from .export import (
    email_scorecard,
    email_scorecards,
    export_all,
    export_dataset,
    export_index,
    export_scorecards,
    stream_email_scorecards,
)
from .incidents import (
    bulk_approve_incidents,
    delete_incident_report,
    incident_list,
    incident_screenshot_download,
    match_incident,
    review_incidents,
    submit_incident_report,
    view_incident_report,
)
from .injects import (
    approve_inject_feedback,
    bulk_approve_inject_feedback,
    inject_grades_bulk_approve,
    inject_grades_review,
    inject_grading,
    review_inject_feedback,
    save_inject_feedback,
)
from .leaderboard import (
    _CategoryRank,
    _compute_scorecard_stats,
    _InjectStat,
    _Neighbor,
    _ScorecardStats,
    _ServiceStat,
    leaderboard,
    scorecard,
    scorecard_pdf,
)
from .orange import (
    bulk_approve_orange_adjustments,
    orange_team_redirect,
    review_orange,
    submit_orange_check,
)
from .red_team import (
    _normalize_red_score_post,
    api_user_ip_pools,
    bulk_approve_red_scores,
    delete_red_score,
    ip_pool_create,
    ip_pool_delete,
    ip_pool_edit,
    ip_pool_list,
    leave_red_score,
    red_screenshot_download,
    red_team_findings,
    red_team_scores,
    submit_red_score,
    view_red_score,
)

__all__ = [
    "leaderboard",
    "scorecard",
    "scorecard_pdf",
    "_compute_scorecard_stats",
    "_CategoryRank",
    "_InjectStat",
    "_ServiceStat",
    "_Neighbor",
    "_ScorecardStats",
    "_normalize_red_score_post",
    "red_team_findings",
    "red_team_scores",
    "bulk_approve_red_scores",
    "submit_red_score",
    "view_red_score",
    "delete_red_score",
    "leave_red_score",
    "red_screenshot_download",
    "ip_pool_list",
    "ip_pool_create",
    "ip_pool_edit",
    "ip_pool_delete",
    "api_user_ip_pools",
    "orange_team_redirect",
    "review_orange",
    "submit_orange_check",
    "bulk_approve_orange_adjustments",
    "submit_incident_report",
    "incident_list",
    "view_incident_report",
    "delete_incident_report",
    "incident_screenshot_download",
    "review_incidents",
    "bulk_approve_incidents",
    "match_incident",
    "inject_grading",
    "inject_grades_review",
    "inject_grades_bulk_approve",
    "review_inject_feedback",
    "save_inject_feedback",
    "approve_inject_feedback",
    "bulk_approve_inject_feedback",
    "scoring_config",
    "sync_metadata",
    "sync_scores",
    "recalculate_scores",
    "export_index",
    "export_dataset",
    "export_all",
    "export_scorecards",
    "email_scorecard",
    "email_scorecards",
    "stream_email_scorecards",
    "api_scores",
    "api_team_detail",
    "api_attack_types",
]
