# Generated by Django 6.1.1 on 2026-10-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_drop_team_max_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
