# Generated by Django 6.1.1 on 2026-10-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_school_info_password_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='password',
            field=models.CharField(blank=True, help_text="The team account's current Authentik password, sent in packets. Change it with Reset Password on the team's page.", max_length=100),
        ),
    ]
