# Generated by Django 6.1.1 on 2026-09-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_discord_task_result_forget_dashboard_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordtask',
            name='task_type',
            field=models.CharField(choices=[('post_comment', 'Post Comment to Thread'), ('broadcast_message', 'Broadcast Message'), ('sync_member_roles', "Sync a Member's Roles"), ('setup_team_infrastructure', 'Setup Team Infrastructure'), ('log_to_channel', 'Log to Ops Channel'), ('post_ticket_update', 'Post Ticket Update to Thread'), ('ticket_created_web', 'Ticket Created via Web'), ('sync_roles', 'Sync Roles from Authentik Groups'), ('add_user_to_thread', 'Add User to Thread'), ('cleanup_competition', 'Clean Up Competition')], max_length=50),
        ),
    ]
