# Generated by Django 5.2.17 on 2026-09-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_add_region_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip', '-attempted_at'], name='registratio_ip_34f2a9_idx')],
            },
        ),
    ]
