# Generated by Django 5.2.12 on 2026-04-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0034_add_orange_check_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringtemplate',
            name='inject_modifier',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Direct scaling modifier for injects (overrides weight-based calculation)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='orange_modifier',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Direct scaling modifier for orange team (overrides weight-based calculation)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='service_modifier',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Direct scaling modifier for service (overrides weight-based calculation)', max_digits=10, null=True),
        ),
    ]
